In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import seaborn as sns
sns.set()

In [2]:
data = pd.read_csv('1.02. Multiple linear regression.csv')
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [3]:
reg = LinearRegression()

In [4]:
y = data['GPA']
x = data.drop(['GPA'], axis=1)

In [6]:
reg.fit(x,y)

LinearRegression()

In [7]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [8]:
reg.intercept_

0.29603261264909353

## Determining the adjusted r^2

In [11]:
the_r2 = reg.score(x,y)
the_r2

0.4066811952814282

In [10]:
x.shape

(84, 2)

In [15]:
n = x.shape[0]
p = x.shape[1]

r2 = 1 - (1-the_r2)*(n-1)/(n-p-1)
r2

0.39203134825134

Feature selection to determine which variables do or don't improve the model

In [16]:
from sklearn.feature_selection import f_regression

In [17]:
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

The f_regression method calculated the f-statistic (first array), and the corresponding
p values for the f-statistics

In [19]:
p_values = f_regression(x,y)[1]
p_values.round(3)

array([0.   , 0.676])

In [24]:
summary_table = pd.DataFrame(data=x.columns.values, columns=['Features'])
summary_table

Features
0         SAT
1  Rand 1,2,3

In [27]:
summary_table['Coefficients'] = reg.coef_
summary_table['p-values'] = p_values
summary_table

Features  Coefficients      p-values
0         SAT      0.001654  7.199518e-11
1  Rand 1,2,3     -0.008270  6.762914e-01